### ISSUE TITLE
Run code formatters in workflows

### ISSUE THREAD

**Issue by rouille** [kasparm/YegorCallCenter#3]
I would recommend that you create a workflow that will check that your code is correctly formatted. Since you have already defined the `checkformatting` and `flake8` commands in your **tox.ini** file, enclosing in a **lint.yml** file located in **.github/workflows** the following should do the job:
```
name: Lint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  formatting:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python -m pip install --upgrade tox
      - run: tox -e checkformatting
  flake8:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: python -m pip install --upgrade tox
      - run: tox -e flake8
```
